spring.application.name=busbuddy

server.address=0.0.0.0
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}

logging.level.org.springframework.data.mongodb=INFO

spring.main.allow-circular-references=true